# Generated by Django 4.2.6 on 2023-10-18 20:14

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ehealth_record.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('firstname', models.CharField(default='', max_length=60)),
                ('lastname', models.CharField(default='', max_length=60)),
                ('role', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_advisor', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('data_join', models.DateTimeField(default=django.utils.timezone.now)),
                ('code_agency', models.IntegerField(blank=True, default=0, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', ehealth_record.models.UserCustomManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ailment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('added_by', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('appointment_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_appointment_consultant', to=settings.AUTH_USER_MODEL, verbose_name='Related Appointment Consultant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_appointment_patient', to=settings.AUTH_USER_MODEL, verbose_name='Related Appointment Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('prescription', models.CharField(max_length=255)),
                ('added_by', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('ailment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealth_record.ailment')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_consultant', to=settings.AUTH_USER_MODEL, verbose_name='Related Consultant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('role', models.CharField(default='', max_length=20)),
                ('sex', models.CharField(default='', max_length=10)),
                ('marital_status', models.CharField(default='', max_length=10)),
                ('h_address', models.CharField(default='', max_length=200)),
                ('w_address', models.CharField(default='', max_length=200)),
                ('lga', models.CharField(default=0, max_length=5)),
                ('state', models.CharField(default=0, max_length=5)),
                ('country', models.CharField(default=0, max_length=5)),
                ('dob', models.DateTimeField()),
                ('picture', models.ImageField(upload_to='img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Appointment_Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date_time', models.DateTimeField()),
                ('defered_date_time', models.DateTimeField()),
                ('added_by', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealth_record.appointment')),
            ],
        ),
    ]
