# Generated by Django 4.2.6 on 2023-10-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_record', '0002_remove_profile_dob_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=60),
        ),
    ]
