# Generated by Django 4.2.6 on 2023-10-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_record', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
