# Generated by Django 4.2.6 on 2023-10-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_record', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='added_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
