# Generated by Django 4.2.6 on 2023-10-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_record', '0006_alter_appointment_added_by_alter_appointment_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='prescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
