# Generated by Django 4.2.6 on 2023-10-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_record', '0008_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='consultant',
        ),
        migrations.AddField(
            model_name='record',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_state', to='ehealth_record.state', verbose_name='State Residing'),
        ),
    ]
